name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          repository: android/kernel_common
          ref: android14-6.1
          path: kernel/source

      - name: Inject MediaTek drivers for Panda PAU0F
        run: |
          cd kernel/source
          echo "CONFIG_WLAN_VENDOR_MEDIATEK=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_MT76_CORE=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_MT76_USB=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_MT76x02_USB=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_MT76x2u=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_MT7921U=y" >> arch/arm64/configs/gki_defconfig
     - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: ./kernel/source/
          config: gki_defconfig
          arch: arm64
          aosp-clang: true
          aosp-gcc: true
          anykernel3: true
